name: Continous integeration

on:
  pull_request:
    types: [assigned, opened, reopened, synchronize, edited]
  push:
    branches:
      - feat/inspire/*
      - develop
      - main
      - master

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: checking the linting
        run: yarn lint
