name: Continous integeration

on:
  pull_request:
    types: [assigned, opened, reopened, synchronize, edited]
  push:
    branches:
      - feat/inspire/*
      - develop
      - main
      - master

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install npm dependencies
        run: yarn
      - name: checking the linting
        run: yarn lint
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install npm dependencies
        run: yarn --frozen-lockfile
      - name: Checking Testing
        run: yarn test
  Build:
    needs: [Linting, Testing]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install npm dependencies
        run: yarn --frozen-lockfile
      - name: Checking Testing
        run: yarn build
